// Generated by js_of_ocaml 3.1.0
(function(h){"use strict";var
bl="%Li",bm=" : flags Open_text and Open_binary are not compatible",bF="Cant find canvas \n",bW=254,$=255,bu=-34,bv="Sys_error",aj=".",bK=224,ai="+",ay=65535,bV="Invalid_argument",bA='"',K=16777215,bJ=250,ak=1024,bP="draw.ml",bQ="%u",bt="%d",aM="jsError",bE="%li",bU="%ni",bk="input",bs=57343,bD=785140586,aO=127,bT=512,br=982028505,bz="End_of_file",by=120,T=" ",bx="Failure",bI="infinity",aQ="e",bg="Undefined_recursive_module",bO=" : flags Open_rdonly and Open_wronly are not compatible",bN="([^/]*)",W="-",bj="Stack_overflow",aN="nan",b="",v=128,bq="canvas",aP="^",bo=240,bp=2048,bC=56320,bH=100,bM=" : file already exists",E="0",x=248,bi="Not_found",bB="Assert_failure",U="/",bn="0x",bR="Sys_blocked_io",bS="fd ",bf="%i",bL="Out_of_memory",bG="Match_failure",bh="static/",d="camlinternalFormat.ml",bw="Division_by_zero";function
a0(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
aY(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=ak,a-=ak)f+=e.apply(null,a0(c,d,Math.min(a,ak)));return f}function
am(b){if(h.Uint8Array)var
c=new(h.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
J(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?aY(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?aY(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)am(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}var
aS=J;function
eN(b,a){throw[0,b,a]}function
ad(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
az(a){if(a.t==2)a.c+=ad(a.l-a.c.length,"\0");else
a.c=aY(a.c,0,a.c.length);a.t=0}function
b2(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>aO)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
eT(f){for(var
k=b,d=b,h,g,i,a,c=0,j=f.length;c<j;c++){g=f.charCodeAt(c);if(g<v){for(var
e=c+1;e<j&&(g=f.charCodeAt(e))<v;e++);if(e-c>bT){d.substr(0,1);k+=d;d=b;k+=f.slice(c,e)}else
d+=f.slice(c,e);if(e==j)break;c=e}a=1;if(++c<j&&((i=f.charCodeAt(c))&-64)==v){h=i+(g<<6);if(g<bK){a=h-12416;if(a<v)a=1}else{a=2;if(++c<j&&((i=f.charCodeAt(c))&-64)==v){h=i+(h<<6);if(g<bo){a=h-925824;if(a<bp||a>=55295&&a<57344)a=2}else{a=3;if(++c<j&&((i=f.charCodeAt(c))&-64)==v&&g<245){a=i-63447168+(h<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>ay)d+=String.fromCharCode(55232+(a>>10),bC+(a&1023));else
d+=String.fromCharCode(a);if(d.length>ak){d.substr(0,1);k+=d;d=b}}return k+d}function
eS(a){switch(a.t){case
9:return a.c;default:az(a);case
0:if(b2(a.c)){a.t=9;return a.c}a.t=8;case
8:return eT(a.c)}}function
D(c,a,b){this.t=c;this.c=a;this.l=b}D.prototype.toString=function(){return eS(this)};function
a(a){return new
D(0,a,a.length)}function
b9(c,b){eN(c,a(b))}var
g=[0];function
aa(a){b9(g.Invalid_argument,a)}function
aX(){aa("index out of bounds")}function
en(a,c,b){b&=$;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}am(a)}a.c[c]=b;return 0}function
al(b,a,c){if(a>>>0>=b.l)aX();return en(b,a,c)}function
eY(c,e){var
d=c.length,b=new
Array(d+1),a=0;for(;a<d;a++)b[a]=c[a];b[a]=e;return b}function
X(b,a){if(b.fun)return X(b.fun,a);var
c=b.length,d=a.length,e=c-d;if(e==0)return b.apply(null,a);else
if(e<0)return X(b.apply(null,a0(a,0,c)),a0(a,c,d-c));else
return function(c){return X(b,eY(a,c))}}function
eo(a){if(isFinite(a)){if(Math.abs(a)>=2.22507385850720138e-308)return 0;if(a!=0)return 1;return 2}return isNaN(a)?4:3}function
N(a){if(a<0)aa("Bytes.create");return new
D(a?2:9,b,a)}function
eq(a,d,c,e){if(c>0)if(d==0&&(c>=a.l||a.t==2&&c>=a.c.length))if(e==0){a.c=b;a.t=2}else{a.c=ad(c,String.fromCharCode(e));a.t=c==a.l?0:2}else{if(a.t!=4)am(a);for(c+=d;d<c;d++)a.c[d]=e}return 0}var
ep=eq;function
aT(a){if((a.t&6)!=0)az(a);return a.c}function
aW(d){d=aT(d);var
e=d.length;if(e>31)aa("format_int: format too long");var
a={justify:ai,signstyle:W,filler:T,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
c=0;c<e;c++){var
b=d.charAt(c);switch(b){case"-":a.justify=W;break;case"+":case" ":a.signstyle=b;break;case"0":a.filler=E;break;case"#":a.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":a.width=0;while(b=d.charCodeAt(c)-48,b>=0&&b<=9){a.width=a.width*10+b;c++}c--;break;case".":a.prec=0;c++;while(b=d.charCodeAt(c)-48,b>=0&&b<=9){a.prec=a.prec*10+b;c++}c--;case"d":case"i":a.signedconv=true;case"u":a.base=10;break;case"x":a.base=16;break;case"X":a.base=16;a.uppercase=true;break;case"o":a.base=8;break;case"e":case"f":case"g":a.signedconv=true;a.conv=b;break;case"E":case"F":case"G":a.signedconv=true;a.uppercase=true;a.conv=b.toLowerCase();break}}return a}function
aU(c,g){if(c.uppercase)g=g.toUpperCase();var
f=g.length;if(c.signedconv&&(c.sign<0||c.signstyle!=W))f++;if(c.alternate){if(c.base==8)f+=1;if(c.base==16)f+=2}var
d=b;if(c.justify==ai&&c.filler==T)for(var
e=f;e<c.width;e++)d+=T;if(c.signedconv)if(c.sign<0)d+=W;else
if(c.signstyle!=W)d+=c.signstyle;if(c.alternate&&c.base==8)d+=E;if(c.alternate&&c.base==16)d+=bn;if(c.justify==ai&&c.filler==E)for(var
e=f;e<c.width;e++)d+=E;d+=g;if(c.justify==W)for(var
e=f;e<c.width;e++)d+=T;return a(d)}function
er(i,c){var
a,e=aW(i),d=e.prec<0?6:e.prec;if(c<0||c==0&&1/c==-Infinity){e.sign=-1;c=-c}if(isNaN(c)){a=aN;e.filler=T}else
if(!isFinite(c)){a="inf";e.filler=T}else
switch(e.conv){case"e":var
a=c.toExponential(d),b=a.length;if(a.charAt(b-3)==aQ)a=a.slice(0,b-1)+E+a.slice(b-1);break;case"f":a=c.toFixed(d);break;case"g":d=d?d:1;a=c.toExponential(d-1);var
h=a.indexOf(aQ),g=+a.slice(h+1);if(g<-4||c>=1e+21||c.toFixed(0).length>d){var
b=h-1;while(a.charAt(b)==E)b--;if(a.charAt(b)==aj)b--;a=a.slice(0,b+1)+a.slice(h);b=a.length;if(a.charAt(b-3)==aQ)a=a.slice(0,b-1)+E+a.slice(b-1);break}else{var
f=d;if(g<0){f-=g+1;a=c.toFixed(f)}else
while(a=c.toFixed(f),a.length>d+1)f--;if(f){var
b=a.length-1;while(a.charAt(b)==E)b--;if(a.charAt(b)==aj)b--;a=a.slice(0,b+1)}}break}return aU(e,a)}function
aA(f,d){if(aT(f)==bt)return a(b+d);var
c=aW(f);if(d<0)if(c.signedconv){c.sign=-1;d=-d}else
d>>>=0;var
e=d.toString(c.base);if(c.prec>=0){c.filler=T;var
g=c.prec-e.length;if(g>0)e=ad(g,E)+e}return aU(c,e)}var
eL=0;function
ao(){return eL++}function
eu(a,b){var
c=a[3]<<16,d=b[3]<<16;if(c>d)return 1;if(c<d)return-1;if(a[2]>b[2])return 1;if(a[2]<b[2])return-1;if(a[1]>b[1])return 1;if(a[1]<b[1])return-1;return 0}function
eE(a,b){if(a<b)return-1;if(a==b)return 0;return 1}function
eP(a,b){a.t&6&&az(a);b.t&6&&az(b);return a.c<b.c?-1:a.c>b.c?1:0}function
bZ(a,b,h){var
d=[];for(;;){if(!(h&&a===b))if(a
instanceof
D)if(b
instanceof
D){if(a!==b){var
c=eP(a,b);if(c!=0)return c}}else
return 1;else
if(a
instanceof
Array&&a[0]===(a[0]|0)){var
e=a[0];if(e===bW)e=0;if(e===bJ){a=a[1];continue}else
if(b
instanceof
Array&&b[0]===(b[0]|0)){var
f=b[0];if(f===bW)f=0;if(f===bJ){b=b[1];continue}else
if(e!=f)return e<f?-1:1;else
switch(e){case
248:var
c=eE(a[2],b[2]);if(c!=0)return c;break;case
251:aa("equal: abstract value");case
255:var
c=eu(a,b);if(c!=0)return c;break;default:if(a.length!=b.length)return a.length<b.length?-1:1;if(a.length>1)d.push(a,b,1)}}else
return 1}else
if(b
instanceof
D||b
instanceof
Array&&b[0]===(b[0]|0))return-1;else
if(typeof
a!="number"&&a&&a.compare)return a.compare(b,h);else
if(typeof
a=="function")aa("compare: functional value");else{if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!h)return NaN;if(a==a)return 1;if(b==b)return-1}}if(d.length==0)return 0;var
g=d.pop();b=d.pop();a=d.pop();if(g+1<a.length)d.push(a,b,g+1);a=a[g];b=b[g]}}function
es(a,b){return+(bZ(a,b,false)>=0)}function
eU(f){for(var
g=b,c=g,a,i,d=0,h=f.length;d<h;d++){a=f.charCodeAt(d);if(a<v){for(var
e=d+1;e<h&&(a=f.charCodeAt(e))<v;e++);if(e-d>bT){c.substr(0,1);g+=c;c=b;g+=f.slice(d,e)}else
c+=f.slice(d,e);if(e==h)break;d=e}if(a<bp){c+=String.fromCharCode(192|a>>6);c+=String.fromCharCode(v|a&63)}else
if(a<55296||a>=bs)c+=String.fromCharCode(bK|a>>12,v|a>>6&63,v|a&63);else
if(a>=56319||d+1==h||(i=f.charCodeAt(d+1))<bC||i>bs)c+="\xef\xbf\xbd";else{d++;a=(a<<10)+i-56613888;c+=String.fromCharCode(bo|a>>18,v|a>>12&63,v|a>>6&63,v|a&63)}if(c.length>ak){c.substr(0,1);g+=c;c=b}}return g+c}function
ab(a){var
b=9;if(!b2(a))b=8,a=eU(a);return new
D(b,a,a.length)}function
et(a,d,l){if(!isFinite(a)){if(isNaN(a))return ab(aN);return ab(a>0?bI:"-infinity")}var
j=a==0&&1/a==-Infinity?1:a>=0?0:1;if(j)a=-a;var
e=0;if(a==0);else
if(a<1)while(a<1&&e>-1022){a*=2;e--}else
while(a>=2){a/=2;e++}var
k=e<0?b:ai,f=b;if(j)f=W;else
switch(l){case
43:f=ai;break;case
32:f=T;break;default:break}if(d>=0&&d<13){var
h=Math.pow(2,d*4);a=Math.round(a*h)/h}var
c=a.toString(16);if(d>=0){var
i=c.indexOf(aj);if(i<0)c+=aj+ad(d,E);else{var
g=i+1+d;if(c.length<g)c+=ad(g-c.length,E);else
c=c.substr(0,g)}}return ab(f+bn+c+"p"+k+e.toString(10))}function
ex(a){return(a[3]|a[2]|a[1])==0}function
eA(a){return[$,a&K,a>>24&K,a>>31&ay]}function
b8(d){var
c=d.length,b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[a];return b}function
eB(a,b){var
c=a[1]-b[1],d=a[2]-b[2]+(c>>24),e=a[3]-b[3]+(d>>24);return[$,c&K,d&K,e&ay]}function
b1(a,b){if(a[3]>b[3])return 1;if(a[3]<b[3])return-1;if(a[2]>b[2])return 1;if(a[2]<b[2])return-1;if(a[1]>b[1])return 1;if(a[1]<b[1])return-1;return 0}function
b0(a){a[3]=a[3]<<1|a[2]>>23;a[2]=(a[2]<<1|a[1]>>23)&K;a[1]=a[1]<<1&K}function
ey(a){a[1]=(a[1]>>>1|a[2]<<23)&K;a[2]=(a[2]>>>1|a[3]<<23)&K;a[3]=a[3]>>>1}function
eD(e,f){var
c=0,b=b8(e),a=b8(f),d=[$,0,0,0];while(b1(b,a)>0){c++;b0(a)}while(c>=0){c--;b0(d);if(b1(b,a)>=0){d[1]++;b=eB(b,a)}ey(a)}return[0,d,b]}function
eC(a){return a[1]|a[2]<<24}function
ew(a){return a[3]<<16<0}function
ez(a){var
b=-a[1],c=-a[2]+(b>>24),d=-a[3]+(c>>24);return[$,b&K,c&K,d&ay]}function
ev(h,d){var
a=aW(h);if(a.signedconv&&ew(d)){a.sign=-1;d=ez(d)}var
c=b,i=eA(a.base),g="0123456789abcdef";do{var
f=eD(d,i);d=f[1];c=g.charAt(eC(f[2]))+c}while(!ex(d));if(a.prec>=0){a.filler=T;var
e=a.prec-c.length;if(e>0)c=ad(e,E)+c}return aU(a,c)}var
aB={amp:/&/g,lt:/</g,quot:/\"/g,all:/[&<\"]/};function
b3(a){if(!aB.all.test(a))return a;return a.replace(aB.amp,"&amp;").replace(aB.lt,"&lt;").replace(aB.quot,"&quot;")}function
eF(a){return function(){return arguments.length>0?X(a,arguments):X(a,[undefined])}}function
O(a){return a.l}function
G(a){b9(g.Sys_error,a)}var
P=new
Array();function
aV(d){var
a=P[d];if(!a.opened)G("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&g.fds[a.fd]&&g.fds[a.fd].output){var
c=g.fds[a.fd].output;switch(c.length){case
2:c(d,a.buffer);break;default:c(a.buffer)}}a.buffer=b;return 0}if(h.process&&h.process.cwd)var
an=h.process.cwd().replace(/\\/g,U);else
var
an="/static";if(an.slice(-1)!==U)an+=U;function
eG(a){a=a
instanceof
D?a.toString():a;if(a.charCodeAt(0)!=47)a=an+a;var
e=a.split(U),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
eM(a){a=a
instanceof
D?a.toString():a;G(a+": No such file or directory")}function
eQ(a){return new
D(4,a,a.length)}function
aq(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
B(b,a){if(a>>>0>=b.l)aX();return aq(b,a)}function
Y(a){if(a<0)aa("String.create");return new
D(a?2:9,b,a)}function
A(a){return a.l}function
bX(){}function
t(a){this.data=a}t.prototype=new
bX();t.prototype.truncate=function(a){var
b=this.data;this.data=Y(a|0);J(b,0,this.data,0,a)};t.prototype.length=function(){return A(this.data)};t.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=Y(b+a),f=this.data;this.data=e;J(f,0,this.data,0,c)}J(d,g,this.data,b,a);return 0};t.prototype.read=function(c,a,d,b){var
e=this.length();J(this.data,c,a,d,b);return 0};t.prototype.read_one=function(a){return B(this.data,a)};t.prototype.close=function(){};t.prototype.constructor=t;function
F(b,a){this.content={};this.root=b;this.lookupFun=a}F.prototype.nm=function(a){return this.root+a};F.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
c=this.lookupFun(a(this.root),a(b));if(c!=0)this.content[b]=new
t(c[1])}};F.prototype.exists=function(a){if(a==b)return 1;var
d=a+U,e=new
RegExp(aP+d);for(var
c
in
this.content)if(c.match(e))return 1;this.lookup(a);return this.content[a]?1:0};F.prototype.readdir=function(d){var
g=d==b?b:d+U,h=new
RegExp(aP+g+bN),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};F.prototype.is_dir=function(a){var
e=a==b?b:a+U,f=new
RegExp(aP+e+bN),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};F.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};F.prototype.open=function(a,b){if(b.rdonly&&b.wronly)G(this.nm(a)+bO);if(b.text&&b.binary)G(this.nm(a)+bm);this.lookup(a);if(this.content[a]){if(this.is_dir(a))G(this.nm(a)+" : is a directory");if(b.create&&b.excl)G(this.nm(a)+bM);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
t(Y(0));return this.content[a]}else
eM(this.nm(a))};F.prototype.register=function(c,b){if(this.content[c])G(this.nm(c)+bM);if(b
instanceof
D)this.content[c]=new
t(b);else
if(b
instanceof
Array)this.content[c]=new
t(eQ(b));else
if(b.toString){var
d=a(b.toString());this.content[c]=new
t(d)}};F.prototype.constructor=F;function
bY(a){if(a.t!=4)am(a);return a.c}function
n(a,c,b){b&=$;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}am(a)}a.c[c]=b;return 0}function
eR(b,a,c){if(a>>>0>=b.l)aX();return n(b,a,c)}var
aR=h.Buffer;function
M(a){this.fs=require("fs");this.fd=a}M.prototype=new
bX();M.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};M.prototype.length=function(){return this.fs.fstatSync(this.fd).size};M.prototype.write=function(f,b,c,e){var
a=bY(b);if(!(a
instanceof
h.Uint8Array))a=new(h.Uint8Array)(a);var
d=new
aR(a);this.fs.writeSync(this.fd,d,c,e,f);return 0};M.prototype.read=function(g,d,c,f){var
a=bY(d);if(!(a
instanceof
h.Uint8Array))a=new(h.Uint8Array)(a);var
e=new
aR(a);this.fs.readSync(this.fd,e,c,f,g);for(var
b=0;b<f;b++)eR(d,c+b,e[c+b]);return 0};M.prototype.read_one=function(c){var
b=new(h.Uint8Array)(1),a=new
aR(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};M.prototype.close=function(){this.fs.closeSync(this.fd)};M.prototype.constructor=M;function
L(a){this.fs=require("fs");this.root=a}L.prototype.nm=function(a){return this.root+a};L.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};L.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};L.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};L.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};L.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
M(d)};L.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};L.prototype.constructor=L;var
ac=an.match(/[^\/]*\//)[0],ar=[];if(typeof
module!=="undefined"&&module.exports&&typeof
require!=="undefined")ar.push({path:ac,device:new
L(ac)});else
ar.push({path:ac,device:new
F(ac)});ar.push({path:ac+bh,device:new
F(ac+bh)});function
eZ(b){var
f=eG(b),b=f.join(U),e=b+U,c;for(var
d=0;d<ar.length;d++){var
a=ar[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
b$(e,f){var
b=P[e],d=a(f),c=A(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
eW(a){var
b=h;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
eX(a){var
b=h;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
aC(c,e,d,a){if(g.fds===undefined)g.fds=new
Array();a=a?a:{};var
b={};b.file=d;b.offset=a.append?d.length():0;b.flags=a;b.output=e;g.fds[c]=b;if(!g.fd_last_idx||c>g.fd_last_idx)g.fd_last_idx=c;return c}function
e0(c,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)G(c.toString()+bO);if(a.text&&a.binary)G(c.toString()+bm);var
d=eZ(c),e=d.device.open(d.rest,a),f=g.fd_last_idx?g.fd_last_idx:0;return aC(f+1,b$,e,a)}aC(0,b$,new
t(Y(0)));aC(1,eX,new
t(Y(0)));aC(2,eW,new
t(Y(0)));function
eH(c){var
b=g.fds[c];if(b.flags.wronly)G(bS+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};P[a.fd]=a;return a.fd}function
b4(d){var
c=g.fds[d];if(c.flags.rdonly)G(bS+d+" is readonly");var
a={file:c.file,offset:c.offset,fd:d,opened:true,out:true,buffer:b};P[a.fd]=a;return a.fd}function
eI(){var
b=0;for(var
a=0;a<P.length;a++)if(P[a]&&P[a].opened&&P[a].out)b=[0,P[a].fd,b];return b}function
b5(g,d,h,f){var
a=P[g];if(!a.opened)G("Cannot output to a closed channel");var
c;if(h==0&&A(d)==f)c=d;else{c=Y(f);J(d,h,c,0,f)}var
b=c.toString(),e=b.lastIndexOf("\n");if(e<0)a.buffer+=b;else{a.buffer+=b.substr(0,e+1);aV(g);a.buffer+=b.substr(e+1)}return 0}function
eJ(c,b){var
d=a(String.fromCharCode(b));b5(c,d,0,1);return 0}function
ap(a,b){return+(bZ(a,b,false)!=0)}function
eK(a){return a
instanceof
Array?a[0]:a
instanceof
D?252:1e3}function
H(c,b,a){g[c+1]=b;if(a)g[a]=b}var
b7={};function
eO(a,b){b7[aT(a)]=b;return 0}function
aZ(a){var
b=1;while(a&&a.joo_tramp){a=a.joo_tramp.apply(null,a.joo_args);b++}return a}function
q(b,a){return{joo_tramp:b,joo_args:a}}function
b_(a){return a}function
b6(a){return b7[a]}function
eV(a){if(a
instanceof
Array)return a;if(h.RangeError&&a
instanceof
h.RangeError&&a.message&&a.message.match(/maximum call stack/i))return b_(g.Stack_overflow);if(h.InternalError&&a
instanceof
h.InternalError&&a.message&&a.message.match(/too much recursion/i))return b_(g.Stack_overflow);if(a
instanceof
h.Error&&b6(aM))return[0,b6(aM),a];return[0,g.Failure,ab(String(a))]}function
e(a,b){return a.length==1?a(b):X(a,[b])}function
I(a,b,c){return a.length==2?a(b,c):X(a,[b,c])}var
a3=[x,a(bv),-2],a1=[x,a(bV),-4],m=[x,a(bB),-11];H(11,[x,a(bg),-12],bg);H(10,m,bB);H(9,[x,a(bR),-10],bR);H(8,[x,a(bj),-9],bj);H(7,[x,a(bG),-8],bG);H(6,[x,a(bi),-7],bi);H(5,[x,a(bw),-6],bw);H(4,[x,a(bz),-5],bz);H(3,a1,bV);H(2,[x,a(bx),-3],bx);H(1,a3,bv);H(0,[x,a(bL),-1],bL);var
cb=a("true"),cc=a("false"),cf=a("\\\\"),cg=a("\\'"),ch=a("\\b"),ci=a("\\t"),cj=a("\\n"),ck=a("\\r"),cn=a("String.blit / Bytes.blit_string"),cm=a("Bytes.blit"),cl=a("String.sub / Bytes.sub"),cw=a("%c"),cx=a("%s"),cy=a(bf),cz=a(bE),cA=a(bU),cB=a(bl),cC=a("%f"),cD=a("%B"),cE=a("%{"),cF=a("%}"),cG=a("%("),cH=a("%)"),cI=a("%a"),cJ=a("%t"),cK=a("%?"),cL=a("%r"),cM=a("%_r"),cN=[0,a(d),846,23],cY=[0,a(d),810,21],cQ=[0,a(d),811,21],cZ=[0,a(d),814,21],cR=[0,a(d),815,21],c0=[0,a(d),818,19],cS=[0,a(d),819,19],c1=[0,a(d),822,22],cT=[0,a(d),823,22],c2=[0,a(d),827,30],cU=[0,a(d),828,30],cW=[0,a(d),832,26],cO=[0,a(d),833,26],cX=[0,a(d),842,28],cP=[0,a(d),843,28],cV=[0,a(d),847,23],d6=a(bQ),d4=[0,a(d),1525,4],d5=a("Printf: bad conversion %["),d7=[0,a(d),1593,39],d8=[0,a(d),1616,31],d9=[0,a(d),1617,31],d_=a("Printf: bad conversion %_"),d$=a("@{"),ea=a("@["),d1=a(aN),d2=a(aj),dZ=a("neg_infinity"),d0=a(bI),dU=a("%.12g"),dH=a("%nd"),dI=a("%+nd"),dJ=a("% nd"),dK=a(bU),dL=a("%+ni"),dM=a("% ni"),dN=a("%nx"),dO=a("%#nx"),dP=a("%nX"),dQ=a("%#nX"),dR=a("%no"),dS=a("%#no"),dT=a("%nu"),du=a("%ld"),dv=a("%+ld"),dw=a("% ld"),dx=a(bE),dy=a("%+li"),dz=a("% li"),dA=a("%lx"),dB=a("%#lx"),dC=a("%lX"),dD=a("%#lX"),dE=a("%lo"),dF=a("%#lo"),dG=a("%lu"),dg=a("%Ld"),dh=a("%+Ld"),di=a("% Ld"),dj=a(bl),dk=a("%+Li"),dl=a("% Li"),dm=a("%Lx"),dn=a("%#Lx"),dp=a("%LX"),dq=a("%#LX"),dr=a("%Lo"),ds=a("%#Lo"),dt=a("%Lu"),c5=a(bt),c6=a("%+d"),c7=a("% d"),c8=a(bf),c9=a("%+i"),c_=a("% i"),c$=a("%x"),da=a("%#x"),db=a("%X"),dc=a("%#X"),dd=a("%o"),de=a("%#o"),df=a(bQ),co=a("@]"),cp=a("@}"),cq=a("@?"),cr=a("@\n"),cs=a("@."),ct=a("@@"),cu=a("@%"),cv=a("@"),c3=a("CamlinternalFormat.Type_mismatch"),ee=a("Js.Error"),eh=a("div"),eg=a(bk),el=[0,[11,a(bF),0],a(bF)],em=[0,a(bP),61,8],ek=[0,a(bP),53,17];function
l(a){if(typeof
a==="number")return 0;else
switch(a[0]){case
0:return[0,l(a[1])];case
1:return[1,l(a[1])];case
2:return[2,l(a[1])];case
3:return[3,l(a[1])];case
4:return[4,l(a[1])];case
5:return[5,l(a[1])];case
6:return[6,l(a[1])];case
7:return[7,l(a[1])];case
8:var
c=a[1];return[8,c,l(a[2])];case
9:var
b=a[1];return[9,b,b,l(a[3])];case
10:return[10,l(a[1])];case
11:return[11,l(a[1])];case
12:return[12,l(a[1])];case
13:return[13,l(a[1])];default:return[14,l(a[1])]}}function
u(a,b){if(typeof
a==="number")return b;else
switch(a[0]){case
0:return[0,u(a[1],b)];case
1:return[1,u(a[1],b)];case
2:return[2,u(a[1],b)];case
3:return[3,u(a[1],b)];case
4:return[4,u(a[1],b)];case
5:return[5,u(a[1],b)];case
6:return[6,u(a[1],b)];case
7:return[7,u(a[1],b)];case
8:var
c=a[1];return[8,c,u(a[2],b)];case
9:var
d=a[2],e=a[1];return[9,e,d,u(a[3],b)];case
10:return[10,u(a[1],b)];case
11:return[11,u(a[1],b)];case
12:return[12,u(a[1],b)];case
13:return[13,u(a[1],b)];default:return[14,u(a[1],b)]}}function
k(a,b){if(typeof
a==="number")return b;else
switch(a[0]){case
0:return[0,k(a[1],b)];case
1:return[1,k(a[1],b)];case
2:var
c=a[1];return[2,c,k(a[2],b)];case
3:var
d=a[1];return[3,d,k(a[2],b)];case
4:var
e=a[3],f=a[2],g=a[1];return[4,g,f,e,k(a[4],b)];case
5:var
h=a[3],i=a[2],j=a[1];return[5,j,i,h,k(a[4],b)];case
6:var
l=a[3],m=a[2],n=a[1];return[6,n,m,l,k(a[4],b)];case
7:var
o=a[3],p=a[2],q=a[1];return[7,q,p,o,k(a[4],b)];case
8:var
r=a[3],s=a[2],t=a[1];return[8,t,s,r,k(a[4],b)];case
9:var
u=a[1];return[9,u,k(a[2],b)];case
10:return[10,k(a[1],b)];case
11:var
v=a[1];return[11,v,k(a[2],b)];case
12:var
w=a[1];return[12,w,k(a[2],b)];case
13:var
x=a[2],y=a[1];return[13,y,x,k(a[3],b)];case
14:var
z=a[2],A=a[1];return[14,A,z,k(a[3],b)];case
15:return[15,k(a[1],b)];case
16:return[16,k(a[1],b)];case
17:var
B=a[1];return[17,B,k(a[2],b)];case
18:var
C=a[1];return[18,C,k(a[2],b)];case
19:return[19,k(a[1],b)];case
20:var
D=a[2],E=a[1];return[20,E,D,k(a[3],b)];case
21:var
F=a[1];return[21,F,k(a[2],b)];case
22:return[22,k(a[1],b)];case
23:var
G=a[1];return[23,G,k(a[2],b)];default:var
H=a[2],I=a[1];return[24,I,H,k(a[3],b)]}}function
as(a){throw[0,a1,a]}ao(0);function
aD(a){return 0<=a?a:-a|0}function
a2(d,c){var
a=A(d),e=A(c),b=N(a+e|0);J(d,0,b,0,a);J(c,0,b,a,e);return b}function
ca(a){return a?cb:cc}eH(0);var
cd=b4(1);b4(2);function
at(b,a){return b5(b,a,0,A(a))}function
V(a,c){var
b=N(a);ep(b,0,a,c);return b}function
Q(e,c,d,b,a){if(0<=a)if(0<=c)if(!((A(e)-a|0)<c))if(0<=b)if(!((O(d)-a|0)<b))return J(e,c,d,b,a);return as(cn)}ao(0);var
aE=-6;function
a4(a){return[0,0,N(a)]}function
a5(b,i){var
a=O(b[2]),c=b[1]+i|0,e=a<c?1:0;if(e){var
f=a*2|0,j=es(f,c)?f:c,d=N(j),g=b[2],k=0<=a?(O(g)-a|0)<0?0:(O(d)-a|0)<0?0:(aS(g,0,d,0,a),1):0;if(!k)as(cm);b[2]=d;var
h=0}else
var
h=e;return h}function
ae(a,b){a5(a,1);al(a[2],a[1],b);a[1]=a[1]+1|0;return 0}function
r(a,c){var
b=A(c);a5(a,b);Q(c,0,a[2],a[1],b);a[1]=a[1]+b|0;return 0}function
a6(c){var
a=c[1],d=c[2];if(0<=a)if(!((O(d)-a|0)<0)){var
b=N(a);aS(d,0,b,0,a);return b}return as(cl)}function
aF(b,c){var
a=c;for(;;)if(typeof
a==="number")return 0;else
switch(a[0]){case
0:var
d=a[1];r(b,cw);var
a=d;continue;case
1:var
e=a[1];r(b,cx);var
a=e;continue;case
2:var
f=a[1];r(b,cy);var
a=f;continue;case
3:var
g=a[1];r(b,cz);var
a=g;continue;case
4:var
h=a[1];r(b,cA);var
a=h;continue;case
5:var
i=a[1];r(b,cB);var
a=i;continue;case
6:var
j=a[1];r(b,cC);var
a=j;continue;case
7:var
k=a[1];r(b,cD);var
a=k;continue;case
8:var
l=a[2],m=a[1];r(b,cE);aF(b,m);r(b,cF);var
a=l;continue;case
9:var
n=a[3],o=a[1];r(b,cG);aF(b,o);r(b,cH);var
a=n;continue;case
10:var
p=a[1];r(b,cI);var
a=p;continue;case
11:var
q=a[1];r(b,cJ);var
a=q;continue;case
12:var
s=a[1];r(b,cK);var
a=s;continue;case
13:var
t=a[1];r(b,cL);var
a=t;continue;default:var
u=a[1];r(b,cM);var
a=u;continue}}function
o(a){if(typeof
a==="number")return 0;else
switch(a[0]){case
0:return[0,o(a[1])];case
1:return[1,o(a[1])];case
2:return[2,o(a[1])];case
3:return[3,o(a[1])];case
4:return[4,o(a[1])];case
5:return[5,o(a[1])];case
6:return[6,o(a[1])];case
7:return[7,o(a[1])];case
8:var
b=a[1];return[8,b,o(a[2])];case
9:var
c=a[2],d=a[1];return[9,c,d,o(a[3])];case
10:return[10,o(a[1])];case
11:return[11,o(a[1])];case
12:return[12,o(a[1])];case
13:return[13,o(a[1])];default:return[14,o(a[1])]}}function
s(a){if(typeof
a==="number"){var
v=function(a){return 0},w=function(a){return 0},x=function(a){return 0};return[0,function(a){return 0},x,w,v]}else
switch(a[0]){case
0:var
b=s(a[1]),y=b[4],z=b[3],A=b[2],B=b[1],C=function(a){e(A,0);return 0};return[0,function(a){e(B,0);return 0},C,z,y];case
1:var
d=s(a[1]),D=d[4],E=d[3],F=d[2],G=d[1],H=function(a){e(F,0);return 0};return[0,function(a){e(G,0);return 0},H,E,D];case
2:var
f=s(a[1]),I=f[4],J=f[3],K=f[2],L=f[1],M=function(a){e(K,0);return 0};return[0,function(a){e(L,0);return 0},M,J,I];case
3:var
g=s(a[1]),N=g[4],O=g[3],P=g[2],Q=g[1],R=function(a){e(P,0);return 0};return[0,function(a){e(Q,0);return 0},R,O,N];case
4:var
h=s(a[1]),S=h[4],T=h[3],U=h[2],V=h[1],W=function(a){e(U,0);return 0};return[0,function(a){e(V,0);return 0},W,T,S];case
5:var
i=s(a[1]),X=i[4],Y=i[3],Z=i[2],_=i[1],$=function(a){e(Z,0);return 0};return[0,function(a){e(_,0);return 0},$,Y,X];case
6:var
j=s(a[1]),aa=j[4],ab=j[3],ac=j[2],ad=j[1],ae=function(a){e(ac,0);return 0};return[0,function(a){e(ad,0);return 0},ae,ab,aa];case
7:var
k=s(a[1]),af=k[4],ag=k[3],ah=k[2],ai=k[1],aj=function(a){e(ah,0);return 0};return[0,function(a){e(ai,0);return 0},aj,ag,af];case
8:var
l=s(a[2]),ak=l[4],al=l[3],am=l[2],an=l[1],ao=function(a){e(am,0);return 0};return[0,function(a){e(an,0);return 0},ao,al,ak];case
9:var
ap=a[2],aq=a[1],m=s(a[3]),ar=m[4],as=m[3],at=m[2],au=m[1],n=s(c(o(aq),ap)),av=n[4],aw=n[3],ax=n[2],ay=n[1],az=function(a){e(av,0);e(ar,0);return 0},aA=function(a){e(as,0);e(aw,0);return 0},aB=function(a){e(ax,0);e(at,0);return 0};return[0,function(a){e(au,0);e(ay,0);return 0},aB,aA,az];case
10:var
p=s(a[1]),aC=p[4],aD=p[3],aE=p[2],aF=p[1],aG=function(a){e(aE,0);return 0};return[0,function(a){e(aF,0);return 0},aG,aD,aC];case
11:var
q=s(a[1]),aH=q[4],aI=q[3],aJ=q[2],aK=q[1],aL=function(a){e(aJ,0);return 0};return[0,function(a){e(aK,0);return 0},aL,aI,aH];case
12:var
r=s(a[1]),aM=r[4],aN=r[3],aO=r[2],aP=r[1],aQ=function(a){e(aO,0);return 0};return[0,function(a){e(aP,0);return 0},aQ,aN,aM];case
13:var
t=s(a[1]),aR=t[4],aS=t[3],aT=t[2],aU=t[1],aV=function(a){e(aR,0);return 0},aW=function(a){e(aS,0);return 0},aX=function(a){e(aT,0);return 0};return[0,function(a){e(aU,0);return 0},aX,aW,aV];default:var
u=s(a[1]),aY=u[4],aZ=u[3],a0=u[2],a1=u[1],a2=function(a){e(aY,0);return 0},a3=function(a){e(aZ,0);return 0},a4=function(a){e(a0,0);return 0};return[0,function(a){e(a1,0);return 0},a4,a3,a2]}}function
c(d,b){if(typeof
d==="number")if(typeof
b==="number")return 0;else
switch(b[0]){case
10:var
a=0;break;case
11:var
a=1;break;case
12:var
a=2;break;case
13:var
a=3;break;case
14:var
a=4;break;case
8:var
a=5;break;case
9:var
a=6;break;default:throw[0,m,cN]}else
switch(d[0]){case
0:var
x=d[1];if(typeof
b==="number")var
f=1;else
switch(b[0]){case
0:return[0,c(x,b[1])];case
8:var
a=5,f=0;break;case
9:var
a=6,f=0;break;case
10:var
a=0,f=0;break;case
11:var
a=1,f=0;break;case
12:var
a=2,f=0;break;case
13:var
a=3,f=0;break;case
14:var
a=4,f=0;break;default:var
f=1}if(f)var
a=7;break;case
1:var
y=d[1];if(typeof
b==="number")var
g=1;else
switch(b[0]){case
1:return[1,c(y,b[1])];case
8:var
a=5,g=0;break;case
9:var
a=6,g=0;break;case
10:var
a=0,g=0;break;case
11:var
a=1,g=0;break;case
12:var
a=2,g=0;break;case
13:var
a=3,g=0;break;case
14:var
a=4,g=0;break;default:var
g=1}if(g)var
a=7;break;case
2:var
z=d[1];if(typeof
b==="number")var
h=1;else
switch(b[0]){case
2:return[2,c(z,b[1])];case
8:var
a=5,h=0;break;case
9:var
a=6,h=0;break;case
10:var
a=0,h=0;break;case
11:var
a=1,h=0;break;case
12:var
a=2,h=0;break;case
13:var
a=3,h=0;break;case
14:var
a=4,h=0;break;default:var
h=1}if(h)var
a=7;break;case
3:var
A=d[1];if(typeof
b==="number")var
i=1;else
switch(b[0]){case
3:return[3,c(A,b[1])];case
8:var
a=5,i=0;break;case
9:var
a=6,i=0;break;case
10:var
a=0,i=0;break;case
11:var
a=1,i=0;break;case
12:var
a=2,i=0;break;case
13:var
a=3,i=0;break;case
14:var
a=4,i=0;break;default:var
i=1}if(i)var
a=7;break;case
4:var
B=d[1];if(typeof
b==="number")var
j=1;else
switch(b[0]){case
4:return[4,c(B,b[1])];case
8:var
a=5,j=0;break;case
9:var
a=6,j=0;break;case
10:var
a=0,j=0;break;case
11:var
a=1,j=0;break;case
12:var
a=2,j=0;break;case
13:var
a=3,j=0;break;case
14:var
a=4,j=0;break;default:var
j=1}if(j)var
a=7;break;case
5:var
C=d[1];if(typeof
b==="number")var
k=1;else
switch(b[0]){case
5:return[5,c(C,b[1])];case
8:var
a=5,k=0;break;case
9:var
a=6,k=0;break;case
10:var
a=0,k=0;break;case
11:var
a=1,k=0;break;case
12:var
a=2,k=0;break;case
13:var
a=3,k=0;break;case
14:var
a=4,k=0;break;default:var
k=1}if(k)var
a=7;break;case
6:var
D=d[1];if(typeof
b==="number")var
l=1;else
switch(b[0]){case
6:return[6,c(D,b[1])];case
8:var
a=5,l=0;break;case
9:var
a=6,l=0;break;case
10:var
a=0,l=0;break;case
11:var
a=1,l=0;break;case
12:var
a=2,l=0;break;case
13:var
a=3,l=0;break;case
14:var
a=4,l=0;break;default:var
l=1}if(l)var
a=7;break;case
7:var
E=d[1];if(typeof
b==="number")var
n=1;else
switch(b[0]){case
7:return[7,c(E,b[1])];case
8:var
a=5,n=0;break;case
9:var
a=6,n=0;break;case
10:var
a=0,n=0;break;case
11:var
a=1,n=0;break;case
12:var
a=2,n=0;break;case
13:var
a=3,n=0;break;case
14:var
a=4,n=0;break;default:var
n=1}if(n)var
a=7;break;case
8:var
F=d[2],G=d[1];if(typeof
b==="number")var
q=1;else
switch(b[0]){case
8:var
H=b[1],I=c(F,b[2]);return[8,c(G,H),I];case
10:var
a=0,q=0;break;case
11:var
a=1,q=0;break;case
12:var
a=2,q=0;break;case
13:var
a=3,q=0;break;case
14:var
a=4,q=0;break;default:var
q=1}if(q)throw[0,m,cW];break;case
9:var
J=d[3],K=d[2],L=d[1];if(typeof
b==="number")var
p=1;else
switch(b[0]){case
8:var
a=5,p=0;break;case
9:var
M=b[3],N=b[2],O=b[1],w=s(c(o(K),O)),P=w[4];e(w[2],0);e(P,0);return[9,L,N,c(J,M)];case
10:var
a=0,p=0;break;case
11:var
a=1,p=0;break;case
12:var
a=2,p=0;break;case
13:var
a=3,p=0;break;case
14:var
a=4,p=0;break;default:var
p=1}if(p)throw[0,m,cX];break;case
10:var
Q=d[1];if(typeof
b!=="number"&&10===b[0])return[10,c(Q,b[1])];throw[0,m,cY];case
11:var
R=d[1];if(typeof
b==="number")var
v=1;else
switch(b[0]){case
10:var
a=0,v=0;break;case
11:return[11,c(R,b[1])];default:var
v=1}if(v)throw[0,m,cZ];break;case
12:var
S=d[1];if(typeof
b==="number")var
u=1;else
switch(b[0]){case
10:var
a=0,u=0;break;case
11:var
a=1,u=0;break;case
12:return[12,c(S,b[1])];default:var
u=1}if(u)throw[0,m,c0];break;case
13:var
T=d[1];if(typeof
b==="number")var
t=1;else
switch(b[0]){case
10:var
a=0,t=0;break;case
11:var
a=1,t=0;break;case
12:var
a=2,t=0;break;case
13:return[13,c(T,b[1])];default:var
t=1}if(t)throw[0,m,c1];break;default:var
U=d[1];if(typeof
b==="number")var
r=1;else
switch(b[0]){case
10:var
a=0,r=0;break;case
11:var
a=1,r=0;break;case
12:var
a=2,r=0;break;case
13:var
a=3,r=0;break;case
14:return[14,c(U,b[1])];default:var
r=1}if(r)throw[0,m,c2]}switch(a){case
0:throw[0,m,cQ];case
1:throw[0,m,cR];case
2:throw[0,m,cS];case
3:throw[0,m,cT];case
4:throw[0,m,cU];case
5:throw[0,m,cO];case
6:throw[0,m,cP];default:throw[0,m,cV]}}var
p=[x,c3,ao(0)];function
au(b,a){if(typeof
b==="number")return[0,0,a];else{if(0===b[0])return[0,[0,b[1],b[2]],a];if(typeof
a!=="number"&&2===a[0])return[0,[1,b[1]],a[1]];throw p}}function
af(e,b,d){var
a=au(e,d);if(typeof
b==="number"){if(0===b)return[0,a[1],0,a[2]];var
c=a[2];if(typeof
c!=="number"&&2===c[0])return[0,a[1],1,c[1]];throw p}return[0,a[1],[0,b[1]],a[2]]}function
y(d,c,b){var
a=j(c,b);return[0,[23,d,a[1]],a[2]]}function
j(b,a){if(typeof
b==="number")return[0,0,a];else
switch(b[0]){case
0:if(typeof
a!=="number"&&0===a[0]){var
v=j(b[1],a[1]);return[0,[0,v[1]],v[2]]}break;case
1:if(typeof
a!=="number"&&0===a[0]){var
x=j(b[1],a[1]);return[0,[1,x[1]],x[2]]}break;case
2:var
ag=b[2],z=au(b[1],a),e=z[2],ah=z[1];if(typeof
e!=="number"&&1===e[0]){var
A=j(ag,e[1]);return[0,[2,ah,A[1]],A[2]]}throw p;case
3:var
ai=b[2],B=au(b[1],a),f=B[2],aj=B[1];if(typeof
f!=="number"&&1===f[0]){var
C=j(ai,f[1]);return[0,[3,aj,C[1]],C[2]]}throw p;case
4:var
ak=b[4],al=b[1],g=af(b[2],b[3],a),h=g[3],am=g[2],an=g[1];if(typeof
h!=="number"&&2===h[0]){var
D=j(ak,h[1]);return[0,[4,al,an,am,D[1]],D[2]]}throw p;case
5:var
ao=b[4],aq=b[1],i=af(b[2],b[3],a),k=i[3],ar=i[2],as=i[1];if(typeof
k!=="number"&&3===k[0]){var
E=j(ao,k[1]);return[0,[5,aq,as,ar,E[1]],E[2]]}throw p;case
6:var
at=b[4],av=b[1],m=af(b[2],b[3],a),n=m[3],aw=m[2],ax=m[1];if(typeof
n!=="number"&&4===n[0]){var
F=j(at,n[1]);return[0,[6,av,ax,aw,F[1]],F[2]]}throw p;case
7:var
ay=b[4],az=b[1],o=af(b[2],b[3],a),q=o[3],aA=o[2],aB=o[1];if(typeof
q!=="number"&&5===q[0]){var
G=j(ay,q[1]);return[0,[7,az,aB,aA,G[1]],G[2]]}throw p;case
8:var
aC=b[4],aD=b[1],r=af(b[2],b[3],a),s=r[3],aE=r[2],aF=r[1];if(typeof
s!=="number"&&6===s[0]){var
H=j(aC,s[1]);return[0,[8,aD,aF,aE,H[1]],H[2]]}throw p;case
9:var
aG=b[2],I=au(b[1],a),t=I[2],aH=I[1];if(typeof
t!=="number"&&7===t[0]){var
J=j(aG,t[1]);return[0,[9,aH,J[1]],J[2]]}throw p;case
10:var
K=j(b[1],a);return[0,[10,K[1]],K[2]];case
11:var
aI=b[1],L=j(b[2],a);return[0,[11,aI,L[1]],L[2]];case
12:var
aJ=b[1],M=j(b[2],a);return[0,[12,aJ,M[1]],M[2]];case
13:if(typeof
a!=="number"&&8===a[0]){var
N=a[1],aK=a[2],aL=b[3],aM=b[1];if(ap([0,b[2]],[0,N]))throw p;var
O=j(aL,aK);return[0,[13,aM,N,O[1]],O[2]]}break;case
14:if(typeof
a!=="number"&&9===a[0]){var
P=a[1],aN=a[3],aO=b[3],aP=b[2],aQ=b[1],aR=[0,l(P)];if(ap([0,l(aP)],aR))throw p;var
Q=j(aO,l(aN));return[0,[14,aQ,P,Q[1]],Q[2]]}break;case
15:if(typeof
a!=="number"&&10===a[0]){var
R=j(b[1],a[1]);return[0,[15,R[1]],R[2]]}break;case
16:if(typeof
a!=="number"&&11===a[0]){var
S=j(b[1],a[1]);return[0,[16,S[1]],S[2]]}break;case
17:var
aS=b[1],T=j(b[2],a);return[0,[17,aS,T[1]],T[2]];case
18:var
U=b[2],u=b[1];if(0===u[0]){var
Y=u[1],aW=Y[2],Z=j(Y[1],a),aX=Z[1],_=j(U,Z[2]);return[0,[18,[0,[0,aX,aW]],_[1]],_[2]]}var
$=u[1],aY=$[2],aa=j($[1],a),aZ=aa[1],ab=j(U,aa[2]);return[0,[18,[1,[0,aZ,aY]],ab[1]],ab[2]];case
19:if(typeof
a!=="number"&&13===a[0]){var
V=j(b[1],a[1]);return[0,[19,V[1]],V[2]]}break;case
20:if(typeof
a!=="number"&&1===a[0]){var
aT=b[2],aU=b[1],W=j(b[3],a[1]);return[0,[20,aU,aT,W[1]],W[2]]}break;case
21:if(typeof
a!=="number"&&2===a[0]){var
aV=b[1],X=j(b[2],a[1]);return[0,[21,aV,X[1]],X[2]]}break;case
23:var
d=b[2],c=b[1];if(typeof
c==="number")switch(c){case
0:return y(c,d,a);case
1:return y(c,d,a);case
2:if(typeof
a!=="number"&&14===a[0]){var
ac=j(d,a[1]);return[0,[23,2,ac[1]],ac[2]]}throw p;default:return y(c,d,a)}else
switch(c[0]){case
0:return y(c,d,a);case
1:return y(c,d,a);case
2:return y(c,d,a);case
3:return y(c,d,a);case
4:return y(c,d,a);case
5:return y(c,d,a);case
6:return y(c,d,a);case
7:return y(c,d,a);case
8:return y([8,c[1],c[2]],d,a);case
9:var
a0=c[1],ad=w(c[2],d,a),ae=ad[2];return[0,[23,[9,a0,ad[1]],ae[1]],ae[2]];case
10:return y(c,d,a);default:return y(c,d,a)}}throw p}function
w(b,d,a){if(typeof
b==="number")return[0,0,j(d,a)];else
switch(b[0]){case
0:if(typeof
a!=="number"&&0===a[0]){var
h=w(b[1],d,a[1]);return[0,[0,h[1]],h[2]]}break;case
1:if(typeof
a!=="number"&&1===a[0]){var
i=w(b[1],d,a[1]);return[0,[1,i[1]],i[2]]}break;case
2:if(typeof
a!=="number"&&2===a[0]){var
k=w(b[1],d,a[1]);return[0,[2,k[1]],k[2]]}break;case
3:if(typeof
a!=="number"&&3===a[0]){var
m=w(b[1],d,a[1]);return[0,[3,m[1]],m[2]]}break;case
4:if(typeof
a!=="number"&&4===a[0]){var
n=w(b[1],d,a[1]);return[0,[4,n[1]],n[2]]}break;case
5:if(typeof
a!=="number"&&5===a[0]){var
q=w(b[1],d,a[1]);return[0,[5,q[1]],q[2]]}break;case
6:if(typeof
a!=="number"&&6===a[0]){var
r=w(b[1],d,a[1]);return[0,[6,r[1]],r[2]]}break;case
7:if(typeof
a!=="number"&&7===a[0]){var
t=w(b[1],d,a[1]);return[0,[7,t[1]],t[2]]}break;case
8:if(typeof
a!=="number"&&8===a[0]){var
u=a[1],D=a[2],E=b[2];if(ap([0,b[1]],[0,u]))throw p;var
v=w(E,d,D);return[0,[8,u,v[1]],v[2]]}break;case
9:if(typeof
a!=="number"&&9===a[0]){var
f=a[2],g=a[1],F=a[3],G=b[3],H=b[2],I=b[1],J=[0,l(g)];if(ap([0,l(I)],J))throw p;var
K=[0,l(f)];if(ap([0,l(H)],K))throw p;var
x=s(c(o(g),f)),L=x[4];e(x[2],0);e(L,0);var
y=w(l(G),d,F),M=y[2];return[0,[9,g,f,o(y[1])],M]}break;case
10:if(typeof
a!=="number"&&10===a[0]){var
z=w(b[1],d,a[1]);return[0,[10,z[1]],z[2]]}break;case
11:if(typeof
a!=="number"&&11===a[0]){var
A=w(b[1],d,a[1]);return[0,[11,A[1]],A[2]]}break;case
13:if(typeof
a!=="number"&&13===a[0]){var
B=w(b[1],d,a[1]);return[0,[13,B[1]],B[2]]}break;case
14:if(typeof
a!=="number"&&14===a[0]){var
C=w(b[1],d,a[1]);return[0,[14,C[1]],C[2]]}break}throw p}function
z(k,i,a){var
b=A(a),j=0<=i?k:0,d=aD(i);if(d<=b)return a;var
l=2===j?48:32,c=V(d,l);switch(j){case
0:Q(a,0,c,0,b);break;case
1:Q(a,0,c,d-b|0,b);break;default:if(0<b){if(43===B(a,0))var
e=1;else
if(45===B(a,0))var
e=1;else
if(32===B(a,0))var
e=1;else
var
g=0,e=0;if(e){al(c,0,B(a,0));Q(a,1,c,(d-b|0)+1|0,b-1|0);var
g=1}}else
var
g=0;if(!g){if(1<b)if(48===B(a,0)){if(by===B(a,1))var
h=1;else
if(88===B(a,1))var
h=1;else
var
f=0,h=0;if(h){al(c,1,B(a,1));Q(a,2,c,(d-b|0)+2|0,b-2|0);var
f=1}}else
var
f=0;else
var
f=0;if(!f)Q(a,0,c,d-b|0,b)}}return c}function
Z(j,b){var
c=aD(j),a=A(b),d=B(b,0);if(58<=d)var
e=71<=d?5<(d-97|0)>>>0?1:0:65<=d?0:1;else{if(32===d)var
f=1;else
if(43<=d)switch(d-43|0){case
5:if(a<(c+2|0))if(1<a){var
k=by===B(b,1)?0:88===B(b,1)?0:1;if(!k){var
h=V(c+2|0,48);al(h,1,B(b,1));Q(b,2,h,(c-a|0)+4|0,a-2|0);return h}}var
e=0,f=0;break;case
0:case
2:var
f=1;break;case
1:case
3:case
4:var
e=1,f=0;break;default:var
e=0,f=0}else
var
e=1,f=0;if(f){if(a<(c+1|0)){var
g=V(c+1|0,48);al(g,0,d);Q(b,1,g,(c-a|0)+2|0,a-1|0);return g}var
e=1}}if(!e)if(a<c){var
i=V(c,48);Q(b,0,i,c-a|0,a);return i}return b}function
c4(d){var
j=0;for(;;){if(A(d)<=j)var
x=0;else{var
g=aq(d,j);if(32<=g){var
r=g+bu|0;if(58<r>>>0)if(93<=r)var
s=0,l=0;else
var
l=1;else
if(56<(r-1|0)>>>0)var
s=1,l=0;else
var
l=1;if(l){var
j=j+1|0;continue}}else
var
s=11<=g?13===g?1:0:8<=g?1:0;var
x=s?1:1}if(x){var
a=[0,0],v=O(d)-1|0,B=0;if(!(v<0)){var
i=B;for(;;){var
f=aq(d,i);if(32<=f){var
p=f+bu|0;if(58<p>>>0)if(93<=p)var
m=0,o=0;else
var
o=1;else
if(56<(p-1|0)>>>0)var
m=1,o=0;else
var
o=1;if(o)var
q=1,m=2}else
var
m=11<=f?13===f?1:0:8<=f?1:0;switch(m){case
0:var
q=4;break;case
1:var
q=2;break}a[1]=a[1]+q|0;var
E=i+1|0;if(v!==i){var
i=E;continue}break}}if(a[1]===O(d)){var
t=O(d),u=N(t);aS(d,0,u,0,t);var
k=u}else{var
b=N(a[1]);a[1]=0;var
w=O(d)-1|0,C=0;if(!(w<0)){var
h=C;for(;;){var
c=aq(d,h);if(35<=c)var
e=92===c?1:aO<=c?0:2;else
if(32<=c)var
e=34<=c?1:2;else
if(14<=c)var
e=0;else
switch(c){case
8:n(b,a[1],92);a[1]++;n(b,a[1],98);var
e=3;break;case
9:n(b,a[1],92);a[1]++;n(b,a[1],116);var
e=3;break;case
10:n(b,a[1],92);a[1]++;n(b,a[1],110);var
e=3;break;case
13:n(b,a[1],92);a[1]++;n(b,a[1],114);var
e=3;break;default:var
e=0}switch(e){case
0:n(b,a[1],92);a[1]++;n(b,a[1],48+(c/bH|0)|0);a[1]++;n(b,a[1],48+((c/10|0)%10|0)|0);a[1]++;n(b,a[1],48+(c%10|0)|0);break;case
1:n(b,a[1],92);a[1]++;n(b,a[1],c);break;case
2:n(b,a[1],c);break}a[1]++;var
D=h+1|0;if(w!==h){var
h=D;continue}break}}var
k=b}}else
var
k=d;var
y=A(k),z=V(y+2|0,34);J(k,0,z,1,y);return z}}function
dV(c,b){switch(c){case
0:var
a=c5;break;case
1:var
a=c6;break;case
2:var
a=c7;break;case
3:var
a=c8;break;case
4:var
a=c9;break;case
5:var
a=c_;break;case
6:var
a=c$;break;case
7:var
a=da;break;case
8:var
a=db;break;case
9:var
a=dc;break;case
10:var
a=dd;break;case
11:var
a=de;break;default:var
a=df}return aA(a,b)}function
dW(c,b){switch(c){case
0:var
a=du;break;case
1:var
a=dv;break;case
2:var
a=dw;break;case
3:var
a=dx;break;case
4:var
a=dy;break;case
5:var
a=dz;break;case
6:var
a=dA;break;case
7:var
a=dB;break;case
8:var
a=dC;break;case
9:var
a=dD;break;case
10:var
a=dE;break;case
11:var
a=dF;break;default:var
a=dG}return aA(a,b)}function
dX(c,b){switch(c){case
0:var
a=dH;break;case
1:var
a=dI;break;case
2:var
a=dJ;break;case
3:var
a=dK;break;case
4:var
a=dL;break;case
5:var
a=dM;break;case
6:var
a=dN;break;case
7:var
a=dO;break;case
8:var
a=dP;break;case
9:var
a=dQ;break;case
10:var
a=dR;break;case
11:var
a=dS;break;default:var
a=dT}return aA(a,b)}function
dY(c,b){switch(c){case
0:var
a=dg;break;case
1:var
a=dh;break;case
2:var
a=di;break;case
3:var
a=dj;break;case
4:var
a=dk;break;case
5:var
a=dl;break;case
6:var
a=dm;break;case
7:var
a=dn;break;case
8:var
a=dp;break;case
9:var
a=dq;break;case
10:var
a=dr;break;case
11:var
a=ds;break;default:var
a=dt}return ev(a,b)}function
R(d,v,i){if(16<=d){if(17<=d)switch(d-17|0){case
2:var
l=0;break;case
0:case
3:var
o=43,l=1;break;default:var
o=32,l=1}else
var
l=0;if(!l)var
o=45;var
j=et(i,v,o);if(19<=d){var
m=O(j);if(0===m)return j;var
s=N(m),t=m-1|0,z=0;if(!(t<0)){var
f=z;for(;;){var
h=aq(j,f);if(97<=h)if(122<h)var
q=0;else
var
u=h-32|0,q=1;else
var
q=0;if(!q)var
u=h;n(s,f,u);var
C=f+1|0;if(t!==f){var
f=C;continue}break}}return s}return j}if(15===d)var
w=dU;else{var
D=aD(v);switch(d){case
15:var
c=70;break;case
0:case
1:case
2:var
c=102;break;case
3:case
4:case
5:var
c=101;break;case
6:case
7:case
8:var
c=69;break;case
9:case
10:case
11:var
c=103;break;case
12:case
13:case
14:var
c=71;break;case
16:case
17:case
18:var
c=104;break;default:var
c=72}var
e=a4(16);ae(e,37);switch(d){case
1:case
4:case
7:case
10:case
13:case
17:case
20:ae(e,43);break;case
2:case
5:case
8:case
11:case
14:case
18:case
21:ae(e,32);break}ae(e,46);r(e,a(b+D));ae(e,c);var
w=a6(e)}var
g=er(w,i);if(15===d){var
x=eo(i),E=A(g);if(3===x)return i<0?dZ:d0;if(4<=x)return d1;var
k=0;for(;;){if(k===E)var
y=0;else{var
p=B(g,k)-46|0,F=23<p>>>0?55===p?1:0:21<(p-1|0)>>>0?1:0;if(!F){var
k=k+1|0;continue}var
y=1}return y?g:a2(g,d2)}}return g}function
av(h,g,e,d,i,c,b,a){if(typeof
i==="number"){if(typeof
c==="number")return 0===c?function(c){return f(h,g,[4,e,I(b,a,c)],d)}:function(i,c){return f(h,g,[4,e,Z(i,I(b,a,c))],d)};var
m=c[1];return function(c){return f(h,g,[4,e,Z(m,I(b,a,c))],d)}}else{if(0===i[0]){var
j=i[2],k=i[1];if(typeof
c==="number")return 0===c?function(c){return f(h,g,[4,e,z(k,j,I(b,a,c))],d)}:function(i,c){return f(h,g,[4,e,z(k,j,Z(i,I(b,a,c)))],d)};var
n=c[1];return function(c){return f(h,g,[4,e,z(k,j,Z(n,I(b,a,c)))],d)}}var
l=i[1];if(typeof
c==="number")return 0===c?function(i,c){return f(h,g,[4,e,z(l,i,I(b,a,c))],d)}:function(j,i,c){return f(h,g,[4,e,z(l,j,Z(i,I(b,a,c)))],d)};var
o=c[1];return function(i,c){return f(h,g,[4,e,z(l,i,Z(o,I(b,a,c)))],d)}}}function
aG(h,g,d,c,a,b){if(typeof
a==="number")return function(a){return f(h,g,[4,d,e(b,a)],c)};else{if(0===a[0]){var
i=a[2],j=a[1];return function(a){return f(h,g,[4,d,z(j,i,e(b,a))],c)}}var
k=a[1];return function(i,a){return f(h,g,[4,d,z(k,i,e(b,a))],c)}}}function
ah(g,M,d,L,K){var
b=M,a=L,c=K;for(;;)if(typeof
c==="number")return I(b,d,a);else
switch(c[0]){case
0:var
O=c[1];return function(c){return f(b,d,[5,a,c],O)};case
1:var
P=c[1];return function(c){if(40<=c)if(92===c)var
g=cf,e=2;else
var
e=aO<=c?0:1;else
if(32<=c)if(39<=c)var
g=cg,e=2;else
var
e=1;else
if(14<=c)var
e=0;else
switch(c){case
8:var
g=ch,e=2;break;case
9:var
g=ci,e=2;break;case
10:var
g=cj,e=2;break;case
13:var
g=ck,e=2;break;default:var
e=0}switch(e){case
0:var
h=N(4);n(h,0,92);n(h,1,48+(c/bH|0)|0);n(h,2,48+((c/10|0)%10|0)|0);n(h,3,48+(c%10|0)|0);var
g=h;break;case
1:var
i=N(1);n(i,0,c);var
g=i;break}var
j=A(g),k=V(j+2|0,39);J(g,0,k,1,j);return f(b,d,[4,a,k],P)};case
2:var
Q=c[2],S=c[1];return aG(b,d,a,Q,S,function(a){return a});case
3:return aG(b,d,a,c[2],c[1],c4);case
4:return av(b,d,a,c[4],c[2],c[3],dV,c[1]);case
5:return av(b,d,a,c[4],c[2],c[3],dW,c[1]);case
6:return av(b,d,a,c[4],c[2],c[3],dX,c[1]);case
7:return av(b,d,a,c[4],c[2],c[3],dY,c[1]);case
8:var
r=c[4],s=c[3],u=c[2],t=c[1];if(typeof
u==="number"){if(typeof
s==="number")return 0===s?function(c){return f(b,d,[4,a,R(t,aE,c)],r)}:function(e,c){return f(b,d,[4,a,R(t,e,c)],r)};var
ai=s[1];return function(c){return f(b,d,[4,a,R(t,ai,c)],r)}}else{if(0===u[0]){var
x=u[2],y=u[1];if(typeof
s==="number")return 0===s?function(c){return f(b,d,[4,a,z(y,x,R(t,aE,c))],r)}:function(e,c){return f(b,d,[4,a,z(y,x,R(t,e,c))],r)};var
aj=s[1];return function(c){return f(b,d,[4,a,z(y,x,R(t,aj,c))],r)}}var
B=u[1];if(typeof
s==="number")return 0===s?function(e,c){return f(b,d,[4,a,z(B,e,R(t,aE,c))],r)}:function(g,e,c){return f(b,d,[4,a,z(B,g,R(t,e,c))],r)};var
ak=s[1];return function(e,c){return f(b,d,[4,a,z(B,e,R(t,ak,c))],r)}}case
9:return aG(b,d,a,c[2],c[1],ca);case
10:var
a=[7,a],c=c[1];continue;case
11:var
a=[2,a,c[1]],c=c[2];continue;case
12:var
a=[3,a,c[1]],c=c[2];continue;case
13:var
T=c[3],U=c[2],C=a4(16);aF(C,U);var
H=a6(C);return function(c){return f(b,d,[4,a,H],T)};case
14:var
W=c[3],X=c[2];return function(e){var
g=e[1],c=j(g,l(o(X)));if(typeof
c[2]==="number")return f(b,d,a,k(c[1],W));throw p};case
15:var
Y=c[1];return function(e,c){return f(b,d,[6,a,function(a){return I(e,a,c)}],Y)};case
16:var
Z=c[1];return function(c){return f(b,d,[6,a,c],Z)};case
17:var
a=[0,a,c[1]],c=c[2];continue;case
18:var
w=c[1];if(0===w[0]){var
_=c[2],$=w[1][1],aa=0,b=function(c,d,e){return function(b,a){return f(d,b,[1,c,[0,a]],e)}}(a,b,_),a=aa,c=$;continue}var
ab=c[2],ac=w[1][1],ad=0,b=function(c,d,e){return function(b,a){return f(d,b,[1,c,[1,a]],e)}}(a,b,ab),a=ad,c=ac;continue;case
19:throw[0,m,d4];case
20:var
ae=c[3],af=[8,a,d5];return function(a){return f(b,d,af,ae)};case
21:var
ag=c[2];return function(c){return f(b,d,[4,a,aA(d6,c)],ag)};case
22:var
ah=c[1];return function(c){return f(b,d,[5,a,c],ah)};case
23:var
h=c[2],v=c[1];if(typeof
v==="number")switch(v){case
0:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
1:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
2:throw[0,m,d7];default:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h])}else
switch(v[0]){case
0:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
1:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
2:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
3:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
4:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
5:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
6:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
7:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
8:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);case
9:var
G=v[2];return g<50?aL(g+1|0,b,d,a,G,h):q(aL,[0,b,d,a,G,h]);case
10:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h]);default:return g<50?i(g+1|0,b,d,a,h):q(i,[0,b,d,a,h])}default:var
D=c[3],E=c[1],F=e(c[2],0);return g<50?aK(g+1|0,b,d,a,D,E,F):q(aK,[0,b,d,a,D,E,F])}}function
aL(g,f,e,d,a,b){if(typeof
a==="number")return g<50?i(g+1|0,f,e,d,b):q(i,[0,f,e,d,b]);else
switch(a[0]){case
0:var
h=a[1];return function(a){return C(f,e,d,h,b)};case
1:var
j=a[1];return function(a){return C(f,e,d,j,b)};case
2:var
k=a[1];return function(a){return C(f,e,d,k,b)};case
3:var
l=a[1];return function(a){return C(f,e,d,l,b)};case
4:var
n=a[1];return function(a){return C(f,e,d,n,b)};case
5:var
p=a[1];return function(a){return C(f,e,d,p,b)};case
6:var
r=a[1];return function(a){return C(f,e,d,r,b)};case
7:var
s=a[1];return function(a){return C(f,e,d,s,b)};case
8:var
t=a[2];return function(a){return C(f,e,d,t,b)};case
9:var
v=a[3],w=a[2],x=c(o(a[1]),w);return function(a){return C(f,e,d,u(x,v),b)};case
10:var
y=a[1];return function(c,a){return C(f,e,d,y,b)};case
11:var
z=a[1];return function(a){return C(f,e,d,z,b)};case
12:var
A=a[1];return function(a){return C(f,e,d,A,b)};case
13:throw[0,m,d8];default:throw[0,m,d9]}}function
i(e,c,b,f,a){var
d=[8,f,d_];return e<50?ah(e+1|0,c,b,d,a):q(ah,[0,c,b,d,a])}function
aK(i,c,b,g,a,f,d){if(f){var
j=f[1];return function(f){return d3(c,b,g,a,j,e(d,f))}}var
h=[4,g,d];return i<50?ah(i+1|0,c,b,h,a):q(ah,[0,c,b,h,a])}function
f(a,b,c,d){return aZ(ah(0,a,b,c,d))}function
C(a,b,c,d,e){return aZ(aL(0,a,b,c,d,e))}function
d3(a,b,c,d,e,f){return aZ(aK(0,a,b,c,d,e,f))}function
S(b,h){var
a=h;for(;;)if(typeof
a==="number")return 0;else
switch(a[0]){case
0:var
d=a[2],i=a[1];if(typeof
d==="number")switch(d){case
0:var
c=co;break;case
1:var
c=cp;break;case
2:var
c=cq;break;case
3:var
c=cr;break;case
4:var
c=cs;break;case
5:var
c=ct;break;default:var
c=cu}else
switch(d[0]){case
0:var
c=d[1];break;case
1:var
c=d[1];break;default:var
c=a2(cv,V(1,d[1]))}S(b,i);return at(b,c);case
1:var
f=a[2],g=a[1];if(0===f[0]){var
j=f[1];S(b,g);at(b,d$);var
a=j;continue}var
k=f[1];S(b,g);at(b,ea);var
a=k;continue;case
6:var
n=a[2];S(b,a[1]);return e(n,b);case
7:S(b,a[1]);return aV(b);case
8:var
o=a[2];S(b,a[1]);return as(o);case
2:case
4:var
l=a[2];S(b,a[1]);return at(b,l);default:var
m=a[2];S(b,a[1]);return eJ(b,m)}}var
a7=[0,0];function
a8(a){a7[1]=[0,a,a7[1]];return 0}var
_=h,ag=null,ec=undefined;function
a9(a,b){return a==ag?e(b,0):a}var
a_=true,a$=_.Array,ba=[x,ee,ao(0)],aH=[0,ba,{}],ed=false,eb=eK(aH)===x?aH:aH[1];eO(a(aM),eb);(function(a){throw a});a8(function(a){return a[1]===ba?[0,ab(a[2].toString())]:0});a8(function(a){return a
instanceof
a$?0:[0,ab(a.toString())]});function
aI(b,a){b.appendChild(a);return 0}function
bb(c){return function(a){if(1-(a==ag?1:0)){var
d=e(c,a);if(1-(d|0))a.preventDefault();return d}var
f=event,b=e(c,f);if(1-(b|0))f.returnValue=b;return b}}var
bc="2d",bd=_.document;function
aw(a,b){return a?e(b,a[1]):0}function
aJ(b,a){return b.createElement(a.toString())}var
be=[0,bD];function
ef(f,e,d,c){for(;;){if(0===f)if(0===e)return aJ(d,c);var
h=be[1];if(bD===h){try{var
j=bd.createElement('<input name="x">'),k=j.tagName.toLowerCase()===bk?1:0,m=k?j.name==="x"?1:0:k,i=m}catch(a){var
i=0}var
l=i?br:-1003883683;be[1]=l;continue}if(br<=h){var
a=new
a$();a.push("<",c.toString());aw(f,function(b){a.push(' type="',b3(b),bA);return 0});aw(e,function(b){a.push(' name="',b3(b),bA);return 0});a.push(">");return d.createElement(a.join(b))}var
g=aJ(d,c);aw(f,function(a){return g.type=a});aw(e,function(a){return g.name=a});return g}}ao(0);_.HTMLElement===ec;var
ax=_.document,ei="#BDC3C7",ej="red";_.onload=bb(function(l){function
j(a){throw[0,m,ek]}var
e=a9(ax.getElementById("main"),j);function
k(c){var
a=el[1],b=0;f(function(b,a){S(b,a);return 0},cd,b,a);throw[0,m,em]}var
c=bd.getElementById(bq);if(c==ag)var
g=ag;else
var
i=c.tagName.toLowerCase()===bq?c:ag,g=i;var
b=a9(g,k),d=ax.createDocumentFragment(),a=ef([0,"submit"],0,ax,eg);a.value="reset";a.onclick=bb(function(a){aI(e,aJ(ax,eh));return ed});aI(d,a);aI(e,d);function
h(d){var
c=b.getContext(bc);c.rect(0,0,b.width,b.height);c.fillStyle=ei;c.fill();var
a=b.getContext(bc);a.beginPath();a.arc(v+d,v,16,0,6.28318530717958623,a_);a.fillStyle=ej;a.fill();_.requestAnimationFrame(eF(function(a){return h(d+1)}));return 0}h(0);return a_});function
ce(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{aV(d)}catch(a){a=eV(a);if(a[1]!==a3)throw a}var
a=c;continue}return 0}}ce(eI(0));return}(function(){return this}()));
